### PR TITLE
Fix assert in box codegen.

### LINKED ISSUE #643: Assertion: unexpected CorInfoType passed to GenIR::size
This pops up in one of the new IL tests.

`Assertion failed: (0) && "UNREACHED", file ..\..\..\..\..\tools\llilc\lib\Reader\readerir.cpp, line 1957`

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Closes #643.

When boxing, pass the size instead of the CorType into the argument helper, so if the box type is a value type we have the size available.

Enable the test that was failing with the assert.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@erozenfeld PTAL.

File: include/Reader/readerir.h [hunk 1]
```diff
@@ -794,7 +794,7 @@ class GenIR : public ReaderBase {
   void callMonitorHelper(bool IsEnter);
 
   IRNode *convertToBoxHelperArgumentType(IRNode *Opr,
-                                         CorInfoType CorType) override;
+                                         uint32_t DestSize) override;
```
Comment (erozenfeld) [inline include/Reader/readerir.h]: Nit: can you make the name of the last param the same in reader.h and readerir.h? They are Size and DestSize.

**Comment by erozenfeld** [comment]
LGTM.

File: include/Reader/readerir.h (hunk 1 above)
Comment (AndyAyersMS) [inline include/Reader/readerir.h]: Made both be `DestSize`.
