### PR TITLE
GcInfo: Fix Offsets for NGEN

### LINKED ISSUE #743: GC: Fix instruction offsets in GCTables  for NGEN
For NGEN and AOT scenarios, the Function entry address is relative to start of file (starts from zero). GcInfo's encodeLiveness() expects this as an offset from the allocated code block.

Fix the difference offset so that instruction offsets reported at  safepoints are correct.

### PR DESCRIPTION
**Pull request by swaroop-sridhar**
GcInfoEncoder needs to find the distance (offset) of the
Function entry point to the start of the code section.
For this, it calculated the diffrence between the HotCodeBlock
and the function address reported in __llvm_stackmaps.

However, in an Ngen/AOT build, the FunctionEntry address
recorded in LLVM's StackMap are post-relocation offsets.
Therefore, it cannot be compared to the Start of the CodeBlock
allocated during compilation.

This change fixes this bug by using non-relocated code-block
address for both function-entry and code-block-start.

Fixes #743

### CODE REVIEW

**Comment by swaroop-sridhar** [comment]
@pgavlin: Please review

File: lib/Jit/LLILCJit.cpp [hunk 1]
```diff
@@ -313,8 +313,8 @@ CorJitResult LLILCJit::compileMethod(ICorJitInfo *JitInfo,
                << " method = " << Context.MethodName << '\n';
       }
       GcInfoAllocator GcInfoAllocator;
-      GCInfo GcInfo(&Context, MM.getStackMapSection(), MM.getHotCodeBlock(),
-                    &GcInfoAllocator);
+      GCInfo GcInfo(&Context, MM.getStackMapSection(), &GcInfoAllocator,
+                    *NativeEntry - MM.getHotCodeBlock());
```
Comment (russellhadley) [inline lib/Jit/LLILCJit.cpp]: Should there be some kind of assert that we always get a positive number for the offset?

**Comment by russellhadley** [comment]
Other than the question about future proofing with an assert this LGTM.

**Comment by pgavlin** [comment]
LGTM.
