### PR TITLE
Make float to int conversion more determined.

### LINKED ISSUE #808: Fix Float to Integer Conversion constant folding
In CoreClr test JIT\Regression\CLR-x86-JIT\V1-M10\b05617\b05617
there is the following MSIL:

```
ldc.r4 2.564783e+007
conv.u1
```

The constant loaded has hex value 0x1875AD6 which should truncate to 0xD6 
when converting to u1. However LLILC, using LLVM utilities, is currently
returning 0. Either the LLVM utilities are incorrect, or we are misunderstanding their
defined semantics.

### PR DESCRIPTION
**Pull request by richardlford**
The ECMA-335 spec says that for unchecked floating point to
integer conversion, that if there is overflow then the result
is unspecified. However for compatibility with other jits
we make the result more deterministic. If the target
bit size is less than 64 we first convert to i64 where overflow
is less likely. Then we truncate to the target bit size.

Closes #808 and allows test
\JIT\Regression\CLR-x86-JIT\V1-M10\b05617\b05617.cmd
to pass.

### CODE REVIEW

**Comment by richardlford** [comment]
@erozenfeld, PTAL.

File: lib/Reader/readerir.cpp [hunk 1]
```diff
@@ -5679,8 +5679,26 @@ IRNode *GenIR::conv(ReaderBaseNS::ConvOpcode Opcode, IRNode *Source) {
     Conversion = SourceIsSigned ? LLVMBuilder->CreateSIToFP(Source, TargetTy)
                                 : LLVMBuilder->CreateUIToFP(Source, TargetTy);
   } else if (SourceTy->isFloatingPointTy() && TargetTy->isIntegerTy()) {
-    Conversion = DestIsSigned ? LLVMBuilder->CreateFPToSI(Source, TargetTy)
-                              : LLVMBuilder->CreateFPToUI(Source, TargetTy);
+    // The ECMA-335 spec says that for unchecked floating point to
+    // integer conversion, that if there is overflow then the result
```
Comment (erozenfeld) [inline lib/Reader/readerir.cpp]: 'that' is repeated twice

File: lib/Reader/readerir.cpp [hunk 2]
```diff
@@ -5679,8 +5679,26 @@ IRNode *GenIR::conv(ReaderBaseNS::ConvOpcode Opcode, IRNode *Source) {
...
+    IntegerType *TargetIntegerType = cast<IntegerType>(TargetTy);
+    int TargetBitWidth = TargetIntegerType->getBitWidth();
+    if (TargetBitWidth < 64) {
+      IntegerType *Int64Ty = Type::getInt64Ty(*JitContext->LLVMContext);
+      if (DestIsSigned) {
+        Conversion = LLVMBuilder->CreateFPToSI(Source, Int64Ty);
+      } else {
+        Conversion = LLVMBuilder->CreateFPToUI(Source, Int64Ty);
+      }
+      // Now do the final conversion to the target type.
```
Comment (erozenfeld) [inline lib/Reader/readerir.cpp]: Can you use the ternary operator here for consistency with the 'else' clause below?

**Comment by erozenfeld** [comment]
LGTM with a couple of nits.

File: lib/Reader/readerir.cpp (hunk 1 above)
Comment (richardlford) [inline lib/Reader/readerir.cpp]: Fixed.

File: lib/Reader/readerir.cpp (hunk 2 above)
Comment (richardlford) [inline lib/Reader/readerir.cpp]: Done.

**Comment by richardlford** [comment]
@erozenfeld, I've pushed the (squashed) version with the changes you suggested.

**Comment by richardlford** [comment]
P.S. When I ran the formatter locally it changed the indentation of a couple of
comment lines unrelated to my change.
This is using the latest formatter binaries so hopefully will check out OK in the lab.

**Comment by erozenfeld** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
The formatting change around line 7520 makes no sense to me. Presumably what was there before checked out ok when I submitted it.

**Comment by richardlford** [comment]
@dotnet-bot, test this please.

**Comment by richardlford** [comment]
I rebased and pushed. The rebased version does not have the extraneous formatting change near 7520.

**Comment by richardlford** [comment]
@dotnet-bot, test this please.

**Comment by richardlford** [comment]
The failures were all infrastructure related except the release win64 which is a failing a new ready-to-run test. Since the checked win64 leg passed I'm going to go ahead and merge.
