### PR TITLE
Fix PHI update logic.

### LINKED ISSUE #785: Update all PHI operands corresponding to a predecessor block
Some recent LLVM change exposed a bug in our PHI update logic.

If a block terminator is
br i1 %6, label %7, label %7
and the operand stack is not empty,
we'll create a PHI instruction in the next block with an undef operand:
; <label>:7                                       ; preds = %2, %2
  %8 = phi i32 [ %3, %2 ], [ undef, %2 ]
...
; <label>:9                                       ; preds = %7
  %10 = add i32 %8, 3

We never update the undef in this case.

llvm::removeUnreachableBlocks calls llvm::constantFoldTerminator
and optimizes the br instruction above so that the above code becomes

br label %5

; <label>:5                                       ; preds = %4
  %6 = add i32 undef, 3

which is a problem. This is causing 6 of our tests to fail.

The fix is to update all PHI operands corresponding to a predecessor,
not just one.

### PR DESCRIPTION
**Pull request by erozenfeld**
If a block terminator is
br i1 %6, label %7, label %7
and the operand stack is not empty,
we'll create a PHI instruction in the successor block with an undef operand:
; <label>:7                                       ; preds = %2, %2
  %8 = phi i32 [ %3, %2 ], [ undef, %2 ]
...
; <label>:9                                       ; preds = %7
  %10 = add i32 %8, 3

We never update the undef in this case.

llvm::removeUnreachableBlocks calls llvm::constantFoldTerminator
and optimizes the br instruction above so that the above code becomes

br label %5

; <label>:5                                       ; preds = %4
  %6 = add i32 undef, 3

which is a problem. This was causing 6 of our tests to fail.

The fix is to update all PHI operands corresponding to a predecessor,
not just one.

Closes #785.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@AndyAyersMS or @JosephTremoulet PTAL

File: include/Reader/readerir.h [hunk 1]
```diff
@@ -1412,9 +1412,9 @@ class GenIR : public ReaderBase {
                                unsigned int NumReservedValues,
                                const llvm::Twine &NameStr);
 
-  /// Add a new operand to the PHI instruction. The type of the new operand may
-  /// or may not equal to the type of the PHI instruction. Adjust the types as
-  /// necessary.
+  /// Update all undef placeholders corresponding to the new operand in the
+  /// PHI instruction. The type of the new operand may or may not equal to the
+  //  type of the PHI instruction. Adjust the types as necessary.
```
Comment (AndyAyersMS) [inline include/Reader/readerir.h]: Looks like you lost a `\` here....

**Comment by AndyAyersMS** [comment]
LGTM, just one minor issue with the comment block.

**Comment by mmitche** [comment]
I'll restart this in a second

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

File: include/Reader/readerir.h [hunk 2]
```diff
@@ -1412,12 +1412,13 @@ class GenIR : public ReaderBase {
                                unsigned int NumReservedValues,
                                const llvm::Twine &NameStr);
 
-  /// Add a new operand to the PHI instruction. The type of the new operand may
-  /// or may not equal to the type of the PHI instruction. Adjust the types as
-  /// necessary.
+  /// Update all undef placeholders corresponding to the new operand in the
+  /// PHI instruction. The type of the new operand may or may not equal to the
```
Comment (JosephTremoulet) [inline include/Reader/readerir.h]: pre-existing typo: should be "may or may not be equal to the ..." or "may or may not equal the ..."

File: lib/Reader/readerir.cpp [hunk 3]
```diff
@@ -7462,11 +7462,15 @@ void GenIR::addPHIOperand(PHINode *Phi, Value *NewOperand,
     LLVMBuilder->restoreIP(SavedInsertPoint);
   }
 
-  int BlockIndex = Phi->getBasicBlockIndex(NewBlock);
-  if (BlockIndex >= 0)
-    Phi->setIncomingValue(BlockIndex, NewOperand);
-  else
-    Phi->addIncoming(NewOperand, NewBlock);
+  bool FoundBlockOperand = false;
```
Comment (JosephTremoulet) [inline lib/Reader/readerir.cpp]: Does this generate a warning in release builds?  Might need to wrap this in #ifndef NDEBUG.

**Comment by JosephTremoulet** [comment]
LGTM aside from two nits.

BTW, the verifier would have rejected that PHI node with this check:
```
        // Check to make sure that if there is more than one entry for a
        // particular basic block in this PHI node, that the incoming values are
        // all identical.
```
Should we be running the verifier before we run unreachable code removal so we can catch things like this statically/earlier?

File: lib/Reader/readerir.cpp (hunk 3 above)
Comment (erozenfeld) [inline lib/Reader/readerir.cpp]: No warning in release builds probably because the var is not only initialized but re-assigned later. We do have several warnings about other initialized but not referenced variables in release builds. I'll fix those separately.

**Comment by erozenfeld** [comment]
Yes, I think running the verifier before unreachable code removal is a good idea. Even if do that we should still run it after the reader is done. Hopefully running the verifier twice won't noticeably slow us down. I'll do that change separately.

File: lib/Reader/readerir.cpp (hunk 3 above)
Comment (JosephTremoulet) [inline lib/Reader/readerir.cpp]: > We do have several warnings about other initialized but not referenced variables in release builds. I'll fix those separately.

Thanks.  If that makes us warning-clean, we should probably start building with `-DLLVM_ENABLE_WERROR=ON` in the lab.

File: include/Reader/readerir.h (hunk 2 above)
Comment (erozenfeld) [inline include/Reader/readerir.h]: Fixed.

**Comment by erozenfeld** [comment]
I somehow messed up testing of the fix. The UndefValue assert was incorrect. We visit the successor block twice when the terminator is br i1 %6, label %7, label %7 so we won't see the UndefValue the second time if we fix up both operands the first time. I revised the fix to fix up just one operand each time.

**Comment by erozenfeld** [comment]
@JosephTremoulet PTAL

**Comment by JosephTremoulet** [comment]
LGTM

**Comment by erozenfeld** [comment]
One build leg failed due to some build mutithreading issue. It failed on rerun with the same error. I will go ahead with the merge.
